### ISSUE TITLE
大佬能否添加一个隐藏到桌面托盘的功能

### ISSUE THREAD

**Issue by rkdawn** [jark006/FtpServer#1]
感谢大佬的付出，本来没记录设置功能，没想到几天后就更新出来了，想提出来另一个升级功能
现在好像是只能最小化在任务栏，其实我觉得能隐藏在桌面那最好用，开启后就无感使用了。

**Comment by jark006** [comment]
暂时没计划做隐藏到右下任务栏，以后再考虑

**Comment by Anyhg** [comment]
> 暂时没计划做隐藏到右下任务栏，以后再考虑

再加一个人，求隐藏到右下任务栏的功能，这样就可以无感使用了，挂打印机扫描好用

**Comment by jark006** [comment]
> > 暂时没计划做隐藏到右下任务栏，以后再考虑
> 
> 再加一个人，求隐藏到右下任务栏的功能，这样就可以无感使用了，挂打印机扫描好用

2024.10.13 更新 v1.10:
新增隐藏到任务栏托盘

[https://github.com/jark006/FtpServer/releases](https://github.com/jark006/FtpServer/releases)

**Comment by jark006** [comment]
> 感谢大佬的付出，本来没记录设置功能，没想到几天后就更新出来了，想提出来另一个升级功能 现在好像是只能最小化在任务栏，其实我觉得能隐藏在桌面那最好用，开启后就无感使用了。

2024.10.13 更新 v1.10:
新增隐藏到任务栏托盘

[https://github.com/jark006/FtpServer/releases](https://github.com/jark006/FtpServer/releases)

**Comment by Anyhg** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
