### ISSUE TITLE
FTP路径下的文件夹不能删除

### ISSUE THREAD

**Issue by rkdawn** [jark006/FtpServer#12]
我发现FTP管理下的文件都可以管理，包括文件夹重命名什么的，但是就是无法删除文件夹，不知道是什么原因
另外求老哥推荐一款WIN的FTP文件管理工具，电脑上的资源管理器太难用了，经常卡死。

**Comment by jark006** [comment]
删除失败时，软件有没有相关日志？

ftp客户端推荐WinSCP

**Comment by rkdawn** [comment]
感谢回复，我刚测试了下，想看下有没有什么日志，可以删除了，前几个版本删除几次都不可以，问题已解决，感谢大佬发布了那么多版本，现在都想不到还有什么可以更新的功能了，顺便问下大佬，如果在电脑上看FTP内的视频，只能下载再看吗，我用平板可以直接打开就能播放，感觉电脑也应该也可以才对。

**Comment by jark006** [comment]
可以在线看，只需要软件支持。例如PotPlayer软件：打开->打开远程连接填FTP-IP即可。不过感觉使用不太方便，你可以找找其他视频播放软件试试
