### ISSUE TITLE
linux用户实名羡慕，求一个linux版

### ISSUE THREAD

**Issue by kero990** [jark006/FtpServer#2]
虽然我不懂python，但这个应该改改就能在linux用吧。
跪求改一版linux的

**Comment by jark006** [comment]
> 虽然我不懂python，但这个应该改改就能在linux用吧。
> 跪求改一版linux的

linux端直接用vsftpd更方便啊

**Comment by kero990** [comment]
完全没有界面，需要手填配置文件，还要启动服务
和你这个的设计思路完全背道而驰啊
如果win有一个是我说的这三点，你肯定也懒得用不是吗，为啥不用serv-U呢

**Comment by yh4922** [comment]
可以试试这个
https://github.com/fclairamb/ftpserver
golang 的 二进制文件
