### ISSUE TITLE
日志问题

### ISSUE THREAD

**Issue by bai-xuan** [jark006/FtpServer#3]
零碎文件太多，客户端数据已经拉取完了，日志还没跑完，且cpu会占用很高。
传的是前端项目的node_moudles目录。
希望可以有个选项控制是否打印日志，这一块消耗资源还是很多的；或者其他方案。
感谢大佬的开源

**Comment by jark006** [comment]
我尝试了1.6万个小文件的传输(再多会超过windows Explorer连接数，报错无法分配更多Internet句柄)，没复现出来，不知和你是文件大小差异还是CPU性能差异，我这边是传输完毕时，日志也恰好走到最新的操作记录，没看出延迟。

尝试优化了一下日志线程这块，有空帮忙测试下面这个，给个反馈，谢谢。
[https://github.com/jark006/FtpServer/releases/tag/v1.9Alpha](https://github.com/jark006/FtpServer/releases/tag/v1.9Alpha)

**Comment by bai-xuan** [comment]
好的，一会儿我测试下这个

**Comment by bai-xuan** [comment]
> 我尝试了1.6万个小文件的传输(再多会超过windows Explorer连接数，报错无法分配更多Internet句柄)，没复现出来，不知和你是文件大小差异还是CPU性能差异，我这边是传输完毕时，日志也恰好走到最新的操作记录，没看出延迟。
> 
> 尝试优化了一下日志线程这块，有空帮忙测试下面这个，给个反馈，谢谢。 https://github.com/jark006/FtpServer/releases/tag/v1.9Alpha

好的，一会儿我测试下

**Comment by wyb-cq** [comment]
对中文传输 中文字符显示乱码 无法传输

**Comment by jark006** [comment]
> 对中文传输 中文字符显示乱码 无法传输
> 

换成GBK编码

**Comment by bai-xuan** [comment]
> 我尝试了1.6万个小文件的传输(再多会超过windows Explorer连接数，报错无法分配更多Internet句柄)，没复现出来，不知和你是文件大小差异还是CPU性能差异，我这边是传输完毕时，日志也恰好走到最新的操作记录，没看出延迟。
> 
> 尝试优化了一下日志线程这块，有空帮忙测试下面这个，给个反馈，谢谢。 https://github.com/jark006/FtpServer/releases/tag/v1.9Alpha

测试完成了，这个版本性能要好很多，差不多传输完了日志也打完了，不卡日志了
