### ISSUE TITLE
2024.10.28 更新：FTP文件服务器 v1.12

### ISSUE THREAD

**Issue by rkdawn** [jark006/FtpServer#9]
2024.10.28 更新：FTP文件服务器 v1.12

1. 新增记忆历史路径

_Originally posted by @jark006 in https://github.com/jark006/FtpServer/issues/5#issuecomment-2441786469_
            那大佬能不能再优化下，支持删除旧的路径，因为有些就是临时用一下，哈哈哈

**Comment by jark006** [comment]
已更新
